apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imc-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imc-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: imc-operator-controller-manager
    namespace: imc-operator-system