apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"imc-operator-controller-manager","namespace":"imc-operator-system"}}
  name: imc-operator-controller-manager
  namespace: imc-operator-system